import { getDb } from "../api/queries/connection";
import { actors, subjects, events, eventActors, eventSubjects } from "./schema";

async function seed() {
  const db = getDb();

  // ─── 1. Seed Actors ──────────────────────────────────────────
  const actorData = [
    { name: "Pierre Martin", role: "Lawyer" },
    { name: "Crédit du Nord", role: "Creditor" },
    { name: "Jean Dubois", role: "Huissier" },
    { name: "Sophie Bernard", role: "Accountant" },
    { name: "LocalSoft HR", role: "Recruiter" },
    { name: "Marc Petit", role: "Hiring Manager" },
    { name: "Marie Chen", role: "CTO" },
    { name: "Thomas Leroy", role: "Engineering Lead" },
    { name: "URSSAF", role: "Government Agency" },
    { name: "BNP Paribas", role: "Creditor" },
    { name: "TechCorp HR", role: "Recruiter" },
    { name: "David Moreau", role: "Tech Lead" },
    { name: "Claire Lefebvre", role: "Notaire" },
    { name: "Crédit Mutuel", role: "Creditor" },
    { name: "Médiateur Lambert", role: "Mediator" },
    { name: "Société Générale", role: "Creditor" },
    { name: "Tribunal de Commerce", role: "Court" },
    { name: "Jean Petit", role: "HR Manager" },
    { name: "StartupXYZ", role: "Employer" },
    { name: "Client Alpha", role: "Client" },
    { name: "Client Beta", role: "Client" },
    { name: "Client Gamma", role: "Client" },
    { name: "Client Delta", role: "Client" },
    { name: "Lucas Girard", role: "Subcontractor" },
    { name: "ING Bank", role: "Bank" },
    { name: "Self", role: "Candidate" },
  ];

  const actorMap: Record<string, number> = {};
  for (const actor of actorData) {
    const result = await db.insert(actors).values(actor);
    actorMap[actor.name] = Number(result[0].insertId);
  }
  console.log(`Seeded ${actorData.length} actors`);

  // ─── 2. Seed Subjects ────────────────────────────────────────
  const subjectData = [
    { slug: "creditor-a", name: "Creditor A — Crédit du Nord", category: "debt", description: "Business loan dispute with Crédit du Nord. Initial claim €47,000, settled at 60% over 24 months.", status: "pending" as const },
    { slug: "creditor-b", name: "Creditor B — Société Générale", category: "debt", description: "Credit line dispute with Société Générale. Claim €18,700, court-approved settlement at 55% over 20 months.", status: "resolved" as const },
    { slug: "creditor-c", name: "Creditor C — BNP Paribas", category: "debt", description: "Credit line dispute with BNP Paribas. Claim €23,500, settled at 65% over 18 months.", status: "resolved" as const },
    { slug: "creditor-d", name: "Creditor D — Crédit Mutuel", category: "debt", description: "Loan dispute with Crédit Mutuel. Claim €31,000, mediated settlement at 70% over 30 months.", status: "resolved" as const },
    { slug: "bv", name: "BV Consulting Business", category: "bv", description: "Personal consulting BV established May 2023. Provides technical consulting, cloud architecture, and training services.", status: "open" as const },
    { slug: "job", name: "Employment Journey", category: "job", description: "Career progression from unemployed to Lead Engineer at StartupXYZ.", status: "resolved" as const },
    { slug: "legal", name: "Legal Proceedings", category: "legal", description: "All legal actions related to debt recovery, court proceedings, and settlement negotiations.", status: "resolved" as const },
    { slug: "personal", name: "Personal Finance Recovery", category: "personal", description: "Personal financial recovery journey including budgeting, savings, credit repair, and investment.", status: "resolved" as const },
    { slug: "admin", name: "Administrative Compliance", category: "admin", description: "Tax filings, social security, insurance, and other administrative tasks.", status: "resolved" as const },
  ];

  const subjectMap: Record<string, number> = {};
  for (const sub of subjectData) {
    const result = await db.insert(subjects).values(sub);
    subjectMap[sub.slug] = Number(result[0].insertId);
  }
  console.log(`Seeded ${subjectData.length} subjects`);

  // ─── 3. Seed Events ──────────────────────────────────────────
  const eventInputs = [
    { slug: "ev-2022-01", title: "Initial consultation with debt lawyer", category: "legal", year: 2022, startDate: "2022-01-10", endDate: "2022-01-10", ongoing: false, status: "resolved", description: "First meeting with Maître Pierre Martin to assess the overall debt situation. Reviewed all creditor claims, identified priority actions, and established a legal strategy.", actorNames: ["Pierre Martin"], subjectSlugs: ["legal"], evidence: [{ label: "Consultation Notes", filename: "consultation_2022_01_10.pdf" }, { label: "Action Plan", filename: "action_plan_q1_2022.pdf" }], relatedSlugs: ["ev-2022-02", "ev-2022-04"] },
    { slug: "ev-2022-02", title: "Creditor A files formal claim", category: "debt", year: 2022, startDate: "2022-03-03", endDate: "2022-03-03", ongoing: false, status: "resolved", description: "Creditor A (Crédit du Nord) files a formal claim for €47,000 in outstanding business loans. The claim includes interest accrual and collection fees.", actorNames: ["Crédit du Nord", "Pierre Martin"], subjectSlugs: ["creditor-a"], evidence: [{ label: "Formal Claim Letter", filename: "claim_credit_nord_2022.pdf" }], relatedSlugs: ["ev-2022-01", "ev-2023-01"] },
    { slug: "ev-2022-03", title: "Appointment with huissier for asset evaluation", category: "legal", year: 2022, startDate: "2022-04-18", endDate: "2022-04-18", ongoing: false, status: "resolved", description: "Bailiff evaluates personal and business assets to determine seizure exposure. Vehicle and equipment valued at approximately €12,000.", actorNames: ["Jean Dubois"], subjectSlugs: ["legal"], evidence: [{ label: "Asset Evaluation Report", filename: "asset_eval_apr_2022.pdf" }], relatedSlugs: ["ev-2022-01"] },
    { slug: "ev-2022-04", title: "Debt inventory and prioritization meeting", category: "debt", year: 2022, startDate: "2022-05-12", endDate: "2022-05-12", ongoing: false, status: "resolved", description: "Comprehensive review of all outstanding debts totaling €127,000 across five creditors. Prioritized by interest rate, legal risk, and negotiation potential.", actorNames: ["Pierre Martin", "Sophie Bernard"], subjectSlugs: ["creditor-a", "admin"], evidence: [{ label: "Debt Inventory", filename: "debt_inventory_may_2022.xlsx" }], relatedSlugs: ["ev-2022-01", "ev-2022-02"] },
    { slug: "ev-2022-05", title: "Personal CV update and skills assessment", category: "personal", year: 2022, startDate: "2022-06-01", endDate: "2022-06-15", ongoing: false, status: "resolved", description: "Updated CV with recent project experience and completed online skills assessment. Focused on full-stack development, cloud architecture, and team leadership competencies.", actorNames: ["Self"], subjectSlugs: ["personal", "job"], evidence: [{ label: "Updated CV", filename: "cv_2022_v3.pdf" }], relatedSlugs: ["ev-2022-06"] },
    { slug: "ev-2022-06", title: "First job application — Developer at LocalSoft", category: "job", year: 2022, startDate: "2022-07-10", endDate: "2022-08-05", ongoing: false, status: "blocked", description: "Applied for Mid-Level Developer position at LocalSoft. Reached final interview stage but offer was withdrawn due to company restructuring.", actorNames: ["LocalSoft HR", "Marc Petit"], subjectSlugs: ["job"], evidence: [{ label: "Application Email", filename: "application_localsoft.pdf" }], relatedSlugs: ["ev-2022-05", "ev-2022-07"] },
    { slug: "ev-2022-07", title: "Networking event — Tech Community Meetup", category: "personal", year: 2022, startDate: "2022-08-20", endDate: "2022-08-20", ongoing: false, status: "resolved", description: "Attended local tech meetup and made three valuable connections in the startup ecosystem. Exchanged contacts with two CTOs and one engineering lead.", actorNames: ["Self", "Marie Chen", "Thomas Leroy"], subjectSlugs: ["personal"], evidence: [{ label: "Contact List", filename: "networking_aug_2022.txt" }], relatedSlugs: ["ev-2022-06"] },
    { slug: "ev-2022-08", title: "Quarterly tax filing — Q2 2022", category: "admin", year: 2022, startDate: "2022-09-15", endDate: "2022-09-15", ongoing: false, status: "resolved", description: "Filed quarterly VAT and income tax returns for Q2 2022. Worked with accountant to ensure compliance despite financial difficulties.", actorNames: ["Sophie Bernard"], subjectSlugs: ["admin"], evidence: [{ label: "Q2 Tax Filing", filename: "tax_q2_2022.pdf" }], relatedSlugs: ["ev-2022-09"] },
    { slug: "ev-2022-09", title: "Social security contributions catch-up plan", category: "admin", year: 2022, startDate: "2022-10-01", endDate: "2022-12-31", ongoing: false, status: "resolved", description: "Negotiated a 6-month catch-up plan for overdue social security contributions. Total arrears: €4,800. Structured payments of €800/month starting October.", actorNames: ["URSSAF", "Sophie Bernard"], subjectSlugs: ["admin"], evidence: [{ label: "Payment Plan Agreement", filename: "urssaf_plan_oct_2022.pdf" }], relatedSlugs: ["ev-2022-08"] },
    { slug: "ev-2022-10", title: "Creditor C sends formal notice", category: "debt", year: 2022, startDate: "2022-11-08", endDate: "2022-11-08", ongoing: false, status: "resolved", description: "Creditor C (BNP Paribas) sends formal notice for €23,500 outstanding credit line. 15-day response deadline. Threatens legal action if unpaid.", actorNames: ["BNP Paribas", "Pierre Martin"], subjectSlugs: ["creditor-c"], evidence: [{ label: "Formal Notice", filename: "notice_bnp_nov_2022.pdf" }], relatedSlugs: ["ev-2022-04", "ev-2023-04"] },
    { slug: "ev-2022-11", title: "Insurance policy review and adjustments", category: "admin", year: 2022, startDate: "2022-12-01", endDate: "2022-12-10", ongoing: false, status: "resolved", description: "Reviewed all insurance policies to reduce costs. Cancelled two non-essential policies, adjusted coverage levels on three others. Annual savings: €1,200.", actorNames: ["Self"], subjectSlugs: ["admin"], evidence: [{ label: "Insurance Review", filename: "insurance_review_2022.xlsx" }], relatedSlugs: [] },
    { slug: "ev-2022-12", title: "Year-end financial review", category: "admin", year: 2022, startDate: "2022-12-28", endDate: "2022-12-28", ongoing: false, status: "resolved", description: "Comprehensive year-end financial review with accountant. Total debt reduced by 8% through initial negotiations. Cash flow analysis shows slow but positive trajectory.", actorNames: ["Sophie Bernard", "Pierre Martin"], subjectSlugs: ["admin"], evidence: [{ label: "Year-End Report", filename: "yearend_2022.pdf" }], relatedSlugs: ["ev-2022-04"] },
    { slug: "ev-2023-01", title: "Negotiation meeting with Creditor A", category: "debt", year: 2023, startDate: "2023-02-08", endDate: "2023-02-08", ongoing: false, status: "resolved", description: "Three-hour negotiation at creditor's offices. Agreed on a 60% settlement over 24 months with suspended interest. Payment plan signed. Monthly payment: €1,175.", actorNames: ["Crédit du Nord", "Pierre Martin"], subjectSlugs: ["creditor-a"], evidence: [{ label: "Settlement Agreement", filename: "settlement_credit_nord_feb_2023.pdf" }, { label: "Payment Schedule", filename: "payment_plan_creditor_a.pdf" }], relatedSlugs: ["ev-2022-02", "ev-2023-02"] },
    { slug: "ev-2023-02", title: "First payment to Creditor A under new plan", category: "debt", year: 2023, startDate: "2023-03-01", endDate: "2023-03-01", ongoing: false, status: "resolved", description: "First monthly payment of €1,175 sent to Creditor A under the negotiated settlement plan. Automatic debit set up for recurring payments.", actorNames: ["Crédit du Nord"], subjectSlugs: ["creditor-a"], evidence: [{ label: "Payment Receipt", filename: "payment_mar_2023.pdf" }], relatedSlugs: ["ev-2023-01"] },
    { slug: "ev-2023-03", title: "Job application — Senior Developer at TechCorp", category: "job", year: 2023, startDate: "2023-03-15", endDate: "2023-04-20", ongoing: false, status: "resolved", description: "Submitted application for Senior Full-Stack Developer position at TechCorp. Completed technical interview and coding challenge. Offer received: €68K annually.", actorNames: ["TechCorp HR", "David Moreau"], subjectSlugs: ["job"], evidence: [{ label: "Application", filename: "application_techcorp.pdf" }, { label: "Offer Letter", filename: "offer_techcorp_apr_2023.pdf" }], relatedSlugs: ["ev-2023-05"] },
    { slug: "ev-2023-04", title: "Negotiation with Creditor C (BNP Paribas)", category: "debt", year: 2023, startDate: "2023-04-12", endDate: "2023-05-30", ongoing: false, status: "resolved", description: "Extended negotiation process with BNP Paribas. Initial offer of 50% rejected. Final agreement reached at 65% settlement over 18 months. Monthly payment: €848.", actorNames: ["BNP Paribas", "Pierre Martin"], subjectSlugs: ["creditor-c"], evidence: [{ label: "Settlement Agreement", filename: "settlement_bnp_may_2023.pdf" }], relatedSlugs: ["ev-2022-10", "ev-2023-10"] },
    { slug: "ev-2023-05", title: "Accepted position at TechCorp", category: "job", year: 2023, startDate: "2023-05-01", endDate: "2023-05-01", ongoing: false, status: "resolved", description: "Signed employment contract with TechCorp. Start date: June 1, 2023. Salary: €68K + benefits. Remote-first with quarterly office visits.", actorNames: ["TechCorp"], subjectSlugs: ["job"], evidence: [{ label: "Employment Contract", filename: "contract_techcorp_may_2023.pdf" }], relatedSlugs: ["ev-2023-03"] },
    { slug: "ev-2023-06", title: "BV incorporation paperwork filed", category: "bv", year: 2023, startDate: "2023-05-22", endDate: "2023-06-15", ongoing: false, status: "resolved", description: "Filed articles of incorporation for the new consulting BV. Notaire processed documents. Chamber of Commerce approved. BV officially registered on June 15.", actorNames: ["Claire Lefebvre", "Sophie Bernard"], subjectSlugs: ["bv"], evidence: [{ label: "Articles of Incorporation", filename: "bv_articles_may_2023.pdf" }, { label: "Chamber Certificate", filename: "kvk_certificate_jun_2023.pdf" }], relatedSlugs: ["ev-2023-07"] },
    { slug: "ev-2023-07", title: "BV bank account opened", category: "bv", year: 2023, startDate: "2023-06-20", endDate: "2023-06-20", ongoing: false, status: "resolved", description: "Opened business bank account for the BV at ING. Set up online banking, debit card, and invoicing system. Ready for first client engagement.", actorNames: ["ING Bank"], subjectSlugs: ["bv"], evidence: [{ label: "Account Confirmation", filename: "bank_account_ing_jun_2023.pdf" }], relatedSlugs: ["ev-2023-06"] },
    { slug: "ev-2023-08", title: "Creditor D informal negotiation attempt", category: "debt", year: 2023, startDate: "2023-07-15", endDate: "2023-08-30", ongoing: false, status: "blocked", description: "Attempted informal negotiation with Creditor D (Crédit Mutuel). They refused any settlement below 90% and threatened immediate legal action. Negotiation failed.", actorNames: ["Crédit Mutuel", "Pierre Martin"], subjectSlugs: ["creditor-d"], evidence: [{ label: "Negotiation Notes", filename: "negotiation_credit_mutuel_aug_2023.pdf" }], relatedSlugs: ["ev-2023-13"] },
    { slug: "ev-2023-09", title: "Personal budget restructuring", category: "personal", year: 2023, startDate: "2023-08-01", endDate: "2023-08-15", ongoing: false, status: "resolved", description: "Complete overhaul of personal budget. Cut discretionary spending by 40%. Allocated 60% of new TechCorp salary to debt repayment and savings.", actorNames: ["Self"], subjectSlugs: ["personal"], evidence: [{ label: "Budget Plan", filename: "budget_restructure_aug_2023.xlsx" }], relatedSlugs: ["ev-2023-05"] },
    { slug: "ev-2023-10", title: "First payment to Creditor C under settlement", category: "debt", year: 2023, startDate: "2023-09-01", endDate: "2023-09-01", ongoing: false, status: "resolved", description: "First monthly payment of €848 to BNP Paribas under the May settlement agreement. Combined with Creditor A payment, total monthly debt service now €2,023.", actorNames: ["BNP Paribas"], subjectSlugs: ["creditor-c"], evidence: [{ label: "Payment Receipt", filename: "payment_sep_2023_bnp.pdf" }], relatedSlugs: ["ev-2023-04"] },
    { slug: "ev-2023-11", title: "First BV client pitch", category: "bv", year: 2023, startDate: "2023-09-20", endDate: "2023-10-05", ongoing: false, status: "resolved", description: "Prepared and delivered first client pitch for BV consulting services. Prospective client: small e-commerce startup needing technical architecture review.", actorNames: ["Client Alpha"], subjectSlugs: ["bv"], evidence: [{ label: "Pitch Deck", filename: "pitch_deck_alpha_sep_2023.pdf" }, { label: "Proposal", filename: "proposal_alpha_oct_2023.pdf" }], relatedSlugs: ["ev-2023-12"] },
    { slug: "ev-2023-12", title: "BV first consulting contract signed", category: "bv", year: 2023, startDate: "2023-10-10", endDate: "2023-10-10", ongoing: false, status: "resolved", description: "Signed first BV consulting contract with Client Alpha. Project scope: technical audit and migration strategy. Fee: €6,500. Delivery timeline: 6 weeks.", actorNames: ["Client Alpha"], subjectSlugs: ["bv"], evidence: [{ label: "Contract", filename: "contract_alpha_oct_2023.pdf" }], relatedSlugs: ["ev-2023-11"] },
    { slug: "ev-2023-13", title: "Court summons from Creditor D", category: "legal", year: 2023, startDate: "2023-10-25", endDate: "2023-10-25", ongoing: false, status: "resolved", description: "Received court summons from Crédit Mutuel for €31,000 claim. Court date set for January 2024. Lawyer preparing defense and counter-proposal.", actorNames: ["Crédit Mutuel", "Pierre Martin", "Tribunal de Commerce"], subjectSlugs: ["creditor-d", "legal"], evidence: [{ label: "Court Summons", filename: "summons_credit_mutuel_oct_2023.pdf" }], relatedSlugs: ["ev-2023-08"] },
    { slug: "ev-2023-14", title: "Technical certification — AWS Solutions Architect", category: "job", year: 2023, startDate: "2023-11-01", endDate: "2023-11-20", ongoing: false, status: "resolved", description: "Completed and passed AWS Solutions Architect Professional certification. 3 weeks of intensive study. Exam score: 87%.", actorNames: ["Self"], subjectSlugs: ["job"], evidence: [{ label: "Certificate", filename: "aws_cert_nov_2023.pdf" }], relatedSlugs: ["ev-2023-03"] },
    { slug: "ev-2023-15", title: "Quarterly tax filing — Q3 2023", category: "admin", year: 2023, startDate: "2023-11-15", endDate: "2023-11-15", ongoing: false, status: "resolved", description: "Filed Q3 2023 tax returns including new BV income. First quarter with dual income streams. Accountant confirmed all deductions properly claimed.", actorNames: ["Sophie Bernard"], subjectSlugs: ["admin"], evidence: [{ label: "Q3 Tax Filing", filename: "tax_q3_2023.pdf" }], relatedSlugs: ["ev-2023-06"] },
    { slug: "ev-2023-16", title: "Debt repayment progress review", category: "debt", year: 2023, startDate: "2023-12-10", endDate: "2023-12-10", ongoing: false, status: "resolved", description: "Year-end review of debt repayment progress. Total debt reduced from €127,000 to €98,000. Two creditors under structured payment plans. One in court proceedings.", actorNames: ["Pierre Martin", "Sophie Bernard"], subjectSlugs: ["debt"], evidence: [{ label: "Debt Progress Report", filename: "debt_progress_dec_2023.pdf" }], relatedSlugs: ["ev-2022-12"] },
    { slug: "ev-2023-17", title: "BV service offerings finalized", category: "bv", year: 2023, startDate: "2023-12-15", endDate: "2023-12-20", ongoing: false, status: "resolved", description: "Finalized BV service offerings: technical consulting, cloud architecture, team training, and code review. Created standardized packages and pricing tiers.", actorNames: ["Self"], subjectSlugs: ["bv"], evidence: [{ label: "Service Catalog", filename: "services_bv_dec_2023.pdf" }], relatedSlugs: ["ev-2023-12"] },
    { slug: "ev-2023-18", title: "Year-end financial review 2023", category: "admin", year: 2023, startDate: "2023-12-28", endDate: "2023-12-28", ongoing: false, status: "resolved", description: "Comprehensive year-end review. Total debt reduced by 23%. BV generated €8,500 in first-quarter revenue. Personal salary from TechCorp stable. Positive trajectory confirmed.", actorNames: ["Sophie Bernard"], subjectSlugs: ["admin"], evidence: [{ label: "Year-End Report 2023", filename: "yearend_2023.pdf" }], relatedSlugs: ["ev-2023-16"] },
    { slug: "ev-2024-01", title: "Creditor B escalates to court proceedings", category: "legal", year: 2024, startDate: "2024-01-08", endDate: null, ongoing: true, status: "open", description: "Creditor B (Société Générale) rejects settlement proposal and files for a titre exécutoire. Claim amount: €18,700. Court date set for June 2024.", actorNames: ["Société Générale", "Tribunal de Commerce"], subjectSlugs: ["creditor-b", "legal"], evidence: [{ label: "Court Filing", filename: "filing_sg_jan_2024.pdf" }], relatedSlugs: ["ev-2024-15"] },
    { slug: "ev-2024-02", title: "Technical interview at StartupXYZ", category: "job", year: 2024, startDate: "2024-02-20", endDate: "2024-03-01", ongoing: false, status: "resolved", description: "Completed three-round interview process at StartupXYZ for Lead Engineer role. Offer received March 1 for €72K annually plus equity options.", actorNames: ["Marie Chen", "Jean Petit"], subjectSlugs: ["job"], evidence: [{ label: "Offer Letter", filename: "offer_startupxyz_mar_2024.pdf" }], relatedSlugs: ["ev-2024-03"] },
    { slug: "ev-2024-03", title: "Job transition to StartupXYZ", category: "job", year: 2024, startDate: "2024-04-01", endDate: "2024-04-01", ongoing: false, status: "resolved", description: "Left TechCorp, joined StartupXYZ as Lead Engineer. Salary increase: €4K. Equity package: 0.15% over 4 years. More senior role with team leadership responsibilities.", actorNames: ["StartupXYZ", "TechCorp"], subjectSlugs: ["job"], evidence: [{ label: "New Contract", filename: "contract_startupxyz_apr_2024.pdf" }, { label: "Resignation Letter", filename: "resignation_techcorp.pdf" }], relatedSlugs: ["ev-2024-02"] },
    { slug: "ev-2024-04", title: "BV first invoice issued to Client Alpha", category: "bv", year: 2024, startDate: "2024-04-03", endDate: "2024-04-17", ongoing: false, status: "resolved", description: "First consulting engagement invoice: €8,500 for strategy project delivered to Client Alpha. Paid within 14 days. Milestone for BV cash flow.", actorNames: ["Client Alpha"], subjectSlugs: ["bv"], evidence: [{ label: "Invoice #001", filename: "invoice_001_alpha_apr_2024.pdf" }, { label: "Payment Receipt", filename: "payment_alpha_apr_2024.pdf" }], relatedSlugs: ["ev-2023-12"] },
    { slug: "ev-2024-05", title: "Court hearing — Creditor D case", category: "legal", year: 2024, startDate: "2024-01-25", endDate: "2024-01-25", ongoing: false, status: "resolved", description: "First court hearing for Crédit Mutuel case. Judge encouraged parties to seek mediation. 30-day mediation period granted. Good sign for settlement potential.", actorNames: ["Tribunal de Commerce", "Pierre Martin", "Crédit Mutuel"], subjectSlugs: ["creditor-d", "legal"], evidence: [{ label: "Hearing Notes", filename: "hearing_jan_2024.pdf" }], relatedSlugs: ["ev-2023-13"] },
    { slug: "ev-2024-06", title: "Mediation session with Creditor D", category: "legal", year: 2024, startDate: "2024-02-20", endDate: "2024-03-15", ongoing: false, status: "resolved", description: "Court-appointed mediation with Crédit Mutuel. After three sessions, reached agreement: 70% settlement over 30 months. Monthly payment: €724. Legal fees split 50/50.", actorNames: ["Médiateur Lambert", "Crédit Mutuel", "Pierre Martin"], subjectSlugs: ["creditor-d", "legal"], evidence: [{ label: "Mediation Agreement", filename: "mediation_credit_mutuel_mar_2024.pdf" }], relatedSlugs: ["ev-2024-05"] },
    { slug: "ev-2024-07", title: "BV client acquisition — Client Beta", category: "bv", year: 2024, startDate: "2024-03-20", endDate: "2024-04-05", ongoing: false, status: "resolved", description: "Acquired second BV client through referral from Client Alpha. Client Beta needs cloud migration support. Contract value: €12,000 over 3 months.", actorNames: ["Client Beta", "Client Alpha"], subjectSlugs: ["bv"], evidence: [{ label: "Contract", filename: "contract_beta_apr_2024.pdf" }], relatedSlugs: ["ev-2024-04"] },
    { slug: "ev-2024-08", title: "Personal emergency fund target reached", category: "personal", year: 2024, startDate: "2024-04-15", endDate: "2024-04-15", ongoing: false, status: "resolved", description: "Emergency fund reached target of €5,000. Provides 2-month expense buffer. Reduces financial stress and improves negotiating position with creditors.", actorNames: ["Self"], subjectSlugs: ["personal"], evidence: [{ label: "Account Statement", filename: "emergency_fund_apr_2024.pdf" }], relatedSlugs: ["ev-2023-09"] },
    { slug: "ev-2024-09", title: "Quarterly tax filing — Q1 2024", category: "admin", year: 2024, startDate: "2024-04-20", endDate: "2024-04-20", ongoing: false, status: "resolved", description: "Filed Q1 2024 taxes. BV revenue: €20,500. Personal salary: €18,000. Accountant optimized deductions across both income streams.", actorNames: ["Sophie Bernard"], subjectSlugs: ["admin"], evidence: [{ label: "Q1 Tax Filing", filename: "tax_q1_2024.pdf" }], relatedSlugs: ["ev-2024-04", "ev-2024-07"] },
    { slug: "ev-2024-10", title: "Debt consolidation analysis", category: "debt", year: 2024, startDate: "2024-05-10", endDate: "2024-05-25", ongoing: false, status: "resolved", description: "Analyzed debt consolidation options with accountant. Compared loan refinancing vs. maintaining separate payment plans. Decision: keep separate plans for flexibility.", actorNames: ["Sophie Bernard", "Pierre Martin"], subjectSlugs: ["debt"], evidence: [{ label: "Consolidation Analysis", filename: "consolidation_analysis_may_2024.xlsx" }], relatedSlugs: ["ev-2023-16"] },
    { slug: "ev-2024-11", title: "BV website launch", category: "bv", year: 2024, startDate: "2024-05-15", endDate: "2024-05-15", ongoing: false, status: "resolved", description: "Launched BV website with service descriptions, case studies, and contact form. Professional design by freelance designer. Cost: €1,200.", actorNames: ["Self"], subjectSlugs: ["bv"], evidence: [{ label: "Website Screenshot", filename: "website_launch_may_2024.png" }], relatedSlugs: ["ev-2023-17"] },
    { slug: "ev-2024-12", title: "Job performance review at StartupXYZ", category: "job", year: 2024, startDate: "2024-06-15", endDate: "2024-06-15", ongoing: false, status: "resolved", description: "Six-month performance review. Exceeded expectations on all metrics. Team productivity increased 25% under new leadership. Positive feedback from stakeholders.", actorNames: ["Marie Chen"], subjectSlugs: ["job"], evidence: [{ label: "Performance Review", filename: "review_startupxyz_jun_2024.pdf" }], relatedSlugs: ["ev-2024-03"] },
    { slug: "ev-2024-13", title: "Court date — Creditor B hearing", category: "legal", year: 2024, startDate: "2024-06-20", endDate: "2024-06-20", ongoing: false, status: "pending", description: "Court hearing for Société Générale case. Presented structured repayment proposal. Judge requested additional financial documentation. Next hearing: September 2024.", actorNames: ["Tribunal de Commerce", "Société Générale", "Pierre Martin"], subjectSlugs: ["creditor-b", "legal"], evidence: [{ label: "Hearing Notes", filename: "hearing_sg_jun_2024.pdf" }], relatedSlugs: ["ev-2024-01"] },
    { slug: "ev-2024-14", title: "BV networking event attendance", category: "bv", year: 2024, startDate: "2024-07-10", endDate: "2024-07-10", ongoing: false, status: "resolved", description: "Attended industry conference and collected 15 qualified leads for BV services. Three follow-up meetings scheduled for August.", actorNames: ["Self"], subjectSlugs: ["bv"], evidence: [{ label: "Lead List", filename: "leads_conference_jul_2024.xlsx" }], relatedSlugs: ["ev-2024-11"] },
    { slug: "ev-2024-15", title: "Second court hearing — Creditor B", category: "legal", year: 2024, startDate: "2024-09-15", endDate: "2024-09-15", ongoing: false, status: "resolved", description: "Second hearing for Société Générale case. Submitted additional financial docs. Court approved 55% settlement over 20 months. Monthly payment: €514. Victory.", actorNames: ["Tribunal de Commerce", "Société Générale", "Pierre Martin"], subjectSlugs: ["creditor-b", "legal"], evidence: [{ label: "Court Ruling", filename: "ruling_sg_sep_2024.pdf" }], relatedSlugs: ["ev-2024-01", "ev-2024-13"] },
    { slug: "ev-2024-16", title: "BV third client — Client Gamma", category: "bv", year: 2024, startDate: "2024-08-20", endDate: "2024-09-01", ongoing: false, status: "resolved", description: "Signed third BV client from conference lead. Client Gamma needs DevOps consulting. Contract: €7,500 fixed fee for infrastructure audit and recommendations.", actorNames: ["Client Gamma"], subjectSlugs: ["bv"], evidence: [{ label: "Contract", filename: "contract_gamma_sep_2024.pdf" }], relatedSlugs: ["ev-2024-14"] },
    { slug: "ev-2024-17", title: "Annual insurance review", category: "admin", year: 2024, startDate: "2024-10-01", endDate: "2024-10-10", ongoing: false, status: "resolved", description: "Annual review of all insurance policies. Adjusted coverage to reflect new job and BV income. Added professional liability insurance for consulting work.", actorNames: ["Self"], subjectSlugs: ["admin"], evidence: [{ label: "Insurance Update", filename: "insurance_review_oct_2024.pdf" }], relatedSlugs: ["ev-2022-11"] },
    { slug: "ev-2024-18", title: "Debt milestone — 50% repaid", category: "debt", year: 2024, startDate: "2024-11-15", endDate: "2024-11-15", ongoing: false, status: "resolved", description: "Major milestone: 50% of original debt repaid. Remaining balance: €63,500 across four creditors. All under structured payment plans. No active legal threats.", actorNames: ["Pierre Martin", "Sophie Bernard"], subjectSlugs: ["debt"], evidence: [{ label: "Debt Progress Report", filename: "debt_50pct_nov_2024.pdf" }], relatedSlugs: ["ev-2023-16"] },
    { slug: "ev-2024-19", title: "Year-end financial review 2024", category: "admin", year: 2024, startDate: "2024-12-28", endDate: "2024-12-28", ongoing: false, status: "resolved", description: "Year-end review shows strong progress. Debt down 50%, BV revenue at €52,000 annually, salary stable. Net worth turned positive for first time in 3 years.", actorNames: ["Sophie Bernard"], subjectSlugs: ["admin"], evidence: [{ label: "Year-End Report 2024", filename: "yearend_2024.pdf" }], relatedSlugs: ["ev-2024-18"] },
    { slug: "ev-2024-20", title: "BV 2025 planning session", category: "bv", year: 2024, startDate: "2024-12-20", endDate: "2024-12-22", ongoing: false, status: "resolved", description: "Planned BV strategy for 2025. Target: €75,000 revenue, hire first subcontractor, expand service offerings to include training workshops.", actorNames: ["Self"], subjectSlugs: ["bv"], evidence: [{ label: "2025 Business Plan", filename: "business_plan_2025.pdf" }], relatedSlugs: ["ev-2024-19"] },
    { slug: "ev-2025-01", title: "Court ruling on Creditor B case", category: "legal", year: 2025, startDate: "2025-01-15", endDate: "2025-01-15", ongoing: false, status: "resolved", description: "Court confirms September settlement agreement. Monthly payments of €514 for 20 months. No asset seizure. Final creditor under legal resolution.", actorNames: ["Tribunal de Commerce", "Pierre Martin"], subjectSlugs: ["creditor-b", "legal"], evidence: [{ label: "Final Ruling", filename: "ruling_sg_final_jan_2025.pdf" }], relatedSlugs: ["ev-2024-15"] },
    { slug: "ev-2025-02", title: "New contract with Client Delta", category: "bv", year: 2025, startDate: "2025-02-01", endDate: "2025-02-01", ongoing: true, status: "open", description: "Six-month consulting contract signed: €4,200/month recurring revenue. Project kickoff February 8. First retainer-based client for BV.", actorNames: ["Client Delta"], subjectSlugs: ["bv"], evidence: [{ label: "Contract", filename: "contract_delta_feb_2025.pdf" }], relatedSlugs: ["ev-2024-20"] },
    { slug: "ev-2025-03", title: "Personal job transition to Lead Engineer", category: "personal", year: 2025, startDate: "2025-03-01", endDate: "2025-03-01", ongoing: false, status: "resolved", description: "Promoted to Lead Engineer at StartupXYZ following 18-month performance review. New salary: €85K + equity. Team expanded to 8 engineers.", actorNames: ["StartupXYZ", "Marie Chen"], subjectSlugs: ["job", "personal"], evidence: [{ label: "Promotion Letter", filename: "promotion_mar_2025.pdf" }], relatedSlugs: ["ev-2024-12"] },
    { slug: "ev-2025-04", title: "BV hires first subcontractor", category: "bv", year: 2025, startDate: "2025-03-15", endDate: "2025-03-20", ongoing: false, status: "resolved", description: "Hired first subcontractor for BV — frontend specialist to handle overflow work. Contract rate: €450/day. Enables taking on larger projects.", actorNames: ["Lucas Girard"], subjectSlugs: ["bv"], evidence: [{ label: "Subcontractor Agreement", filename: "subcontractor_lucas_mar_2025.pdf" }], relatedSlugs: ["ev-2025-02"] },
    { slug: "ev-2025-05", title: "Q1 2025 tax filing", category: "admin", year: 2025, startDate: "2025-04-15", endDate: "2025-04-15", ongoing: false, status: "resolved", description: "Filed Q1 2025 taxes. BV revenue: €18,900 (strong start). Personal salary: €21,250. Accountant noted significant improvement in financial position.", actorNames: ["Sophie Bernard"], subjectSlugs: ["admin"], evidence: [{ label: "Q1 Tax Filing", filename: "tax_q1_2025.pdf" }], relatedSlugs: ["ev-2025-02"] },
    { slug: "ev-2025-06", title: "Debt milestone — 70% repaid", category: "debt", year: 2025, startDate: "2025-04-20", endDate: "2025-04-20", ongoing: false, status: "resolved", description: "70% of original debt now repaid. Remaining balance: €38,100. Monthly payments total €3,261 across all creditors. End in sight.", actorNames: ["Sophie Bernard"], subjectSlugs: ["debt"], evidence: [{ label: "Debt Progress Report", filename: "debt_70pct_apr_2025.pdf" }], relatedSlugs: ["ev-2024-18"] },
    { slug: "ev-2025-07", title: "BV training workshop pilot", category: "bv", year: 2025, startDate: "2025-04-25", endDate: "2025-04-25", ongoing: false, status: "resolved", description: "Delivered first training workshop: \"Cloud Architecture Best Practices\" for 12 developers at Client Delta. Fee: €3,500. Plan to offer quarterly workshops.", actorNames: ["Client Delta"], subjectSlugs: ["bv"], evidence: [{ label: "Workshop Materials", filename: "workshop_cloud_apr_2025.pdf" }], relatedSlugs: ["ev-2025-02"] },
    { slug: "ev-2025-08", title: "Personal investment account opened", category: "personal", year: 2025, startDate: "2025-05-01", endDate: "2025-05-01", ongoing: false, status: "resolved", description: "Opened personal investment account with low-cost index fund strategy. Initial deposit: €2,000. Beginning long-term wealth building beyond debt repayment.", actorNames: ["Self"], subjectSlugs: ["personal"], evidence: [{ label: "Account Opening", filename: "investment_account_may_2025.pdf" }], relatedSlugs: ["ev-2024-08"] },
    { slug: "ev-2025-09", title: "Creditor A final payment scheduled", category: "debt", year: 2025, startDate: "2025-05-10", endDate: "2025-05-10", ongoing: false, status: "pending", description: "Scheduled final payment to Creditor A. After 27 months of payments, debt fully settled. Last payment: €1,175. Certificate of full settlement expected within 30 days.", actorNames: ["Crédit du Nord"], subjectSlugs: ["creditor-a"], evidence: [{ label: "Final Payment Receipt", filename: "final_payment_creditor_a_may_2025.pdf" }], relatedSlugs: ["ev-2023-01"] },
    { slug: "ev-2025-10", title: "BV Q2 client pipeline review", category: "bv", year: 2025, startDate: "2025-04-30", endDate: "2025-04-30", ongoing: false, status: "resolved", description: "Q2 pipeline review: 5 qualified prospects, 2 proposals pending, 1 verbal commitment. On track to hit €75K annual revenue target.", actorNames: ["Self"], subjectSlugs: ["bv"], evidence: [{ label: "Pipeline Report", filename: "pipeline_q2_2025.xlsx" }], relatedSlugs: ["ev-2024-20"] },
    { slug: "ev-2025-11", title: "Legal review of all settlement agreements", category: "legal", year: 2025, startDate: "2025-03-01", endDate: "2025-03-10", ongoing: false, status: "resolved", description: "Comprehensive legal review of all active settlement agreements with lawyer. Confirmed all terms being met. No compliance issues. Estimated full debt freedom: March 2027.", actorNames: ["Pierre Martin"], subjectSlugs: ["legal"], evidence: [{ label: "Agreement Review", filename: "agreement_review_mar_2025.pdf" }], relatedSlugs: ["ev-2025-01"] },
    { slug: "ev-2025-12", title: "Salary negotiation at StartupXYZ", category: "job", year: 2025, startDate: "2025-02-15", endDate: "2025-02-28", ongoing: false, status: "resolved", description: "Negotiated salary increase from €78K to €85K as part of promotion package. Also secured additional 5 days PTO and increased training budget to €3,000/year.", actorNames: ["Jean Petit", "Marie Chen"], subjectSlugs: ["job"], evidence: [{ label: "Compensation Letter", filename: "compensation_feb_2025.pdf" }], relatedSlugs: ["ev-2025-03"] },
    { slug: "ev-2025-13", title: "BV brand refresh", category: "bv", year: 2025, startDate: "2025-01-20", endDate: "2025-02-05", ongoing: false, status: "resolved", description: "Completed BV brand refresh with new logo, updated website, and professional marketing materials. Investment: €2,800. Reflects growth from startup to established consultancy.", actorNames: ["Self"], subjectSlugs: ["bv"], evidence: [{ label: "Brand Guidelines", filename: "brand_guidelines_feb_2025.pdf" }], relatedSlugs: ["ev-2024-11"] },
    { slug: "ev-2025-14", title: "Personal credit score recovery", category: "personal", year: 2025, startDate: "2025-05-05", endDate: "2025-05-05", ongoing: false, status: "resolved", description: "Credit score improved from 420 to 680 over 3 years. All payment plans current. No defaults in 18 months. Qualifies for standard financial products again.", actorNames: ["Self"], subjectSlugs: ["personal"], evidence: [{ label: "Credit Report", filename: "credit_report_may_2025.pdf" }], relatedSlugs: ["ev-2023-09"] },
    { slug: "ev-2025-15", title: "Five-year recovery plan assessment", category: "admin", year: 2025, startDate: "2025-05-12", endDate: "2025-05-12", ongoing: false, status: "resolved", description: "Comprehensive assessment of 3.5-year recovery journey. Debt: €127K → €38K. Income: €0 BV → €52K BV + €85K salary. Net worth: negative → positive €45K. Recovery on track.", actorNames: ["Sophie Bernard", "Pierre Martin"], subjectSlugs: ["debt", "personal", "admin"], evidence: [{ label: "Recovery Assessment", filename: "recovery_assessment_may_2025.pdf" }], relatedSlugs: ["ev-2025-06", "ev-2025-14"] },
  ];

  const eventMap: Record<string, number> = {};
  for (const ev of eventInputs) {
    const result = await db.insert(events).values({
      slug: ev.slug,
      title: ev.title,
      category: ev.category,
      year: ev.year,
      startDate: ev.startDate,
      endDate: ev.endDate,
      ongoing: ev.ongoing,
      status: ev.status,
      description: ev.description,
      evidence: ev.evidence,
      relatedSlugs: ev.relatedSlugs,
    });
    const eventId = Number(result[0].insertId);
    eventMap[ev.slug] = eventId;

    // Link actors
    for (const actorName of ev.actorNames) {
      const actorId = actorMap[actorName];
      if (actorId) {
        await db.insert(eventActors).values({ eventId, actorId });
      }
    }

    // Link subjects
    for (const subjectSlug of ev.subjectSlugs) {
      const subjectId = subjectMap[subjectSlug];
      if (subjectId) {
        await db.insert(eventSubjects).values({ eventId, subjectId });
      }
    }
  }

  console.log(`Seeded ${eventInputs.length} events with relationships`);
  console.log("✅ Database seed complete!");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
